[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm install && npx prisma generate && npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
